### ISSUE TITLE
Implicit links are not supported

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#18]
Emacs Muse converts URLs to clickable links: https://www.gnu.org/software/emacs-muse/manual/muse.html#Implicit-Links

**Comment by melmothx** [comment]
That's by design. I found that having implicit links leads to sloppy typeset documents. I believe that should be a choice of the author. However, converting links to the the properly marked up links is supported by the preprocessor. https://metacpan.org/pod/Text::Amuse::Preprocessor#fix_links
