### ISSUE TITLE
Multi-paragraph footnotes

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#19]
I think footnotes-2 testcase is processed incorrectly by Text::Amuse. Emacs Muse does not reorder "This is another paragraph" to the top, it is just a part of the second footnote:

```
<p>My<sup><a class="footref" name="fnr.1" href="#fn.1">1</a></sup> footnote<sup><a class="footref" name="fnr.2" href="#fn.2">2</a></sup>!</p>

<p class="footnote"><a class="footnum" name="fn.1" href="#fnr.1">1.</a> This is
a. pretty</p>

<p class="footnote"><a class="footnum" name="fn.2" href="#fnr.2">2.</a> This is
1. pretty
<p class="verse">
hello yeah<br>
</p>
&lt;script&gt; \latex

<p>This is another paragraph <sup><a class="footref" name="fnr.3" href="#fn.3">3</a></sup> <sup><a class="footref" name="fnr.4" href="#fn.4">4</a></sup></p>

<p class="footnote"><a class="footnum" name="fn.3" href="#fnr.3">3.</a> This is
T. test</p>

<p class="footnote"><a class="footnum" name="fn.4" href="#fnr.4">4.</a> This is</p>

<dl>
<dt><strong>test</strong></dt>
<dd>me it's clear it's a footnote

<dl>
<dt><strong>Test</strong></dt>
<dd>Me
Here we are in a list</dd>
</dl></dd>
</dl>

<ol>
<li>Should be ok</li>
</ol>
```

Text::Amuse places it at the top:
https://github.com/melmothx/text-amuse/blob/11a4e6890f9059e9d2c238c9047fc57c927ddb72/t/testfiles/footnotes-2.exp.html#L7

[Emacs Muse manual on footnotes](https://www.gnu.org/software/emacs-muse/manual/html_node/Footnotes.html#Footnotes) says that footnote definitions are placed at the bottom of the file:
> To define the footnote, place this definition at the bottom of your file.

Threfore, interspersed paragraphs are not part of the document body, they are part of the footnote.

**Comment by melmothx** [comment]
> I think footnotes-2 testcase is processed incorrectly by Text::Amuse. Emacs Muse does not reorder "This is another paragraph" to the top, it is just a part of the second footnote:

> [Emacs Muse manual on footnotes](https://www.gnu.org/software/emacs-muse/manual/html_node/Footnotes.html#Footnotes) says that footnote definitions are placed at the bottom of the file:
> To define the footnote, place this definition at the bottom of your file.
>
> Threfore, interspersed paragraphs are not part of the document body, they are part of the footnote.

This is an incompatibility and, imho, an improvement. Dealing with large
texts (hundred of pages) and large amount of footnotes (hundreds) and
having them in the bottom, is a pain.

See this thread for an explanation why:

https://github.com/melmothx/amusewiki/issues/111

and

https://amusewiki.org/library/working-with-footnotes

-- 
Marco

**Comment by melmothx** [comment]
Btw, multiparagraph footnotes are supported via the `<br>` tag.

**Comment by labdsf** [comment]
`<br>` creates `<br>` tag, not a paragraph, so it is a "multi-line" footnote, not multi-paragraph.

I maintain pandoc Muse reader and writer and try to support both dialects. Now I do it like Emacs Muse: once you start a footnote you can only stop it with end of file or another footnote. I can safely implement something in-between, like allowing footnotes in the end of any section, so you can break footnote with a header. It does not make sense to have headers in footnotes anyway. But it still does not solve the compatibility problem.

Emacs Muse is not maintained, so I resolve most conflicts in favour of Amusewiki syntax, but if I change footnote syntax I need writer to have some way to write pandoc documents without losing semantic information.

What do you think about allowing "continuations" in a way similar to how list items can have multiple paragraphs? If the line after footnote and blank line is indented with number of spaces just as wide as footnote marker, it is considered to be a paragraph within a footnote. Such syntax has all the problems of list items (you can't align text within items with spaces and have to use tags, for example), but no more.

**Comment by melmothx** [comment]
The <br> in a footnote, implementation-wise, is identical to a new paragraph. But ok, it's animplementation detail. I'm thinking about this.

**Comment by melmothx** [comment]
Continuations via identical indentation makes sense and shouldn't be a big problem.

**Comment by melmothx** [comment]
This is mostly done and needs some serious testing + eventually a indentation matching relax, so 1 or 2 spaces more or less will not be relevant (to avoid breaking documents when renumbering the footnotes).

**Comment by melmothx** [comment]
Whitespace tolerance is 1 space more or less, like for lists. Thing is complete.
