### ISSUE TITLE
Two blanklines do not start a new list

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#20]
In Emacs Muse, the following code creates two separate `<ul>` lists:
```
 - Foo


 - Bar
```

If there is only one or no blank lines between items, it creates a single `<ul>` list, while Amusewiki always creates a single list. Without this feature it is impossible to create a sequence of two separate lists.

[Import utility](https://sandbox.amusewiki.org/utils/import), given
```
<ul>
	<li>abc</li>
</ul>

<ul>
	<li>def</li>
	<li>gh</li>
</ul>
```
as an input, produces this:
```
 - abc

 - def

 - gh
```
So it is impossible to separate lists after importing the text.

I don't know of any real use for consequent lists, so it is low-priority, but still a bug.

**Comment by melmothx** [comment]
This is unlikely to be fixed, as multiple empty line are always seen as equivalent to one. a `<br>` tag on a line by itself however will break the list. Will be close by documentation patch.

**Comment by labdsf** [comment]
@melmothx 
> a `<br>` tag on a line by itself however will break the list. Will be close by documentation patch.

I think it is better to suggest using a comment instead of `<br>` in documentation. I checked, separating lists with a comment produces two separate lists. It is better because there will be no empty paragraph with `<br>` tag inside.
