### ISSUE TITLE
[proposal] Endnotes

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#24]
As Text::Amuse is mostly used by Amusewiki, which focuses on archiving books and articles, I think it needs to support both footnotes and endnotes. Endnotes are often used in books to add translator's notes, so it should also be possible to reference endnotes from within footnotes. Without additional syntax it is impossible to typeset endnotes in Muse, while possible in ODT and LaTeX.

What we already have is essentially endnotes. I propose to rename them into "endnotes" in the [manual](https://amusewiki.org/library/manual), make them generate `\endnote` instead of `\footnote` in LaTeX (needs additional package) and add new syntax for footnotes.

For footnotes I suggest to add the following syntax:
```
Footnote reference[*], footnote reference 2[**].

[*] Footnote 1
    with continuation and endnote reference [1].

[**] Footnote 2

     Second paragraph of footnote 2

Footnote reference 3[*]

[*] Footnote 3 with endnote reference [2]

* Notes

[1] Endnote 1

[2] Endnote 2
```

So footnotes can be redefined and nearby footnote definition (searched downwards from reference) is used.

In books footnotes are usually not numbered and reference marks (*, ** etc.) are redefined for each page, while endnotes are globally numbered, so this syntax resembles footnotes in real books.

This change would also solve most problems with managing footnotes and reduce the need for `muse-check-footnotes.pl`, `muse-rearrange-footnotes.pl` scripts.

I have also proposed to add footnote and endnote separation to `pandoc`: jgm/pandoc/issues/4041
All code is there with Docx and ODT support, so it will be possible to add support for footnotes and endnotes to `pandoc` once it is merged.

Existing simple texts which only use endnotes can be left as is, there is no need to convert endnotes into footnotes immediately. A perl script and/or pandoc filter can be created to automate this process later.

**Comment by melmothx** [comment]
Ok, before we start thinking about this, and I'm kind of open to it, we need to clear out some concepts, I think.

I think that endnote/footnote distinction is misleading. Text::Amuse places the footnotes at the end of the text in the HTML, while keeps them in the same page on the PDF, as HTML as no concept of page. So, it's a matter of style, not of logic where they appear. When I see the footnotes placed at the end of a chapter, I usually think it's a typographical missing feature (i.e., they can't typeset them on the same page for whatever reason, so they place them at the end). This greatly harms the reading flow, so I don't see it as feature at all. Actually, I see it as a misfeature.

About "real books". I've seen "real books" with footnote number resetting at each page, at each chapter or never (global numbering). They're all "real books" from mainstream and established publishers, fwiw. Now, given that nowadays the web distribution is first class, having them numbered globally is easier and more correct, as you can reference a paper saying "Footnote 666", instead of "footnote 2 on page 34", page that could very well not exist in another format (HTML), or could be on another page (on EPUB readers).

So, back to us. If we change the existing footnote style, I will be killed by the users (and again, I don't agree on this). So that's a no-go.

On the other hand, what I think we're discussing here is not the placement of the notes, but instead the generation of a second class of footnotes (which could be marked with stars or letters), which are usually used to differentiate the authors' notes from the translator's notes (e.g. critical editions). And on this I agree.

**Comment by labdsf** [comment]
> If we change the existing footnote style, I will be killed by the users (and again, I don't agree on this). So that's a no-go.

Well, moving all notes from footnotes to endnotes will make PDFs unusable. It is probably better to just add a second style of footnote markers for LaTeX output.

> On the other hand, what I think we're discussing here is not the placement of the notes, but instead the generation of a second class of footnotes (which could be marked with stars or letters), which are usually used to differentiate the authors' notes from the translator's notes (e.g. critical editions). And on this I agree.

Maybe to call them something completely different from "footnotes" and "endnotes" then, based on their semantics, or just "primary" and "secondary" notes. I name them footnotes and endnotes because I want to keep it compatible with pandoc, which will be limited to footnotes and endnotes (and maybe margin notes) only anyway as it has to be compatible to many formats, including ODT which only supports footnotes and endnotes.

**Comment by melmothx** [comment]
Package candidate: bigfoot. https://ctan.org/pkg/bigfoot (probably a recent version is required).

**Comment by melmothx** [comment]
Further material:

```
\usepackage{bigfoot}
\usepackage{perpage}
% \usepackage[stable]{footmisc}  % this should not be needed anymore with the arg                                                                                                                                                                                                             
\DeclareNewFootnote{default}
\DeclareNewFootnote{A}[alph]
\MakeSortedPerPage[1]{footnoteA}
```
The various sectioning commands should be turned in the form:

```
\part[TOC]{Hello\footnote{First Second\footnoteA{Test}}\footnoteA{Test}}
\chapter[TOC]{Hello\footnote{First Second\footnoteA{Test}}\footnoteA{Test}}
\section[TOC]{Hello\footnote{First Second\footnoteA{Test}}\footnoteA{Test}}
\subsection[TOC]{Hello\footnote{First Second\footnoteA{Test}}\footnoteA{Test}}
\subsubsection[TOC]{Hello\footnote{First Second\footnoteA{Test}}\footnoteA{Test}}
```

So, using the optional arg in square brackets with the ToC (and running headings) material without the footnotes. This is currently handle by footmisc, but of course doesn't play along with bigfoot.

**Comment by labdsf** [comment]
@melmothx 

From commits it looks like you call "[*]" footnotes "secondary", so "[1]" are going to be "primary". Actually I expected "[*]" notes to be primary for new texts. Numbered footnotes [need additional tools to manage them](https://amusewiki.org/library/working-with-footnotes) when chunks of texts are reordered. So numbered footnotes are more suited for adding commentary to archived texts that are not subject to change.

Maybe it is better not to impose any semantics on footnotes at all (not even calling them primary and secondary) so existing texts can keep legacy notes as primary and new texts can use new style notes. I see adding new footnote style is a chance to make them more usable and fix existing problems we have with numbered notes.

> Now, given that nowadays the web distribution is first class, having them numbered globally is easier and more correct, as you can reference a paper saying "Footnote 666", instead of "footnote 2 on page 34", page that could very well not exist in another format (HTML), or could be on another page (on EPUB readers).

In we talk about web it is possible to reference footnotes by document version and anchor like "#fn11". Even if notes are not numbered, they will get some anchors anyway. Also, they can be globally numbered during compilation even if not numbered in the source.

Also even if both styles can be made equivalent in Text::Amuse, I will have to call some notes "footnotes" and some notes "endnotes" in pandoc Muse reader. If only one style is used (does not matter which one), they can be made "footnotes", but when both of them are used, one of them has to be "endnotes" by default. Adding endnotes support to pandoc was the source of idea to add new footnote style to Muse and I thought to read "[1]" as endnotes, but now it seems inconsistent with your view of them.

If you don't agree that new style is better, then it is better to discuss and redesign them to make them an actual improvement good enough to be used as "primary" for new texts.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> From commits it looks like you call "[*]" footnotes "secondary", so
> "[1]" are going to be "primary". Actually I expected "[*]" notes to be
> primary for new texts. Numbered footnotes [need additional tools to
> manage them](https://amusewiki.org/library/working-with-footnotes)
> when chunks of texts are reordered. So numbered footnotes are more
> suited for adding commentary to archived texts that are not subject to
> change.

A bit of history here. In a primitive Text::Amuse implementation, there
was the rule what the number was merely a decoration, i.e. only the
order counted. As in the WIP branch it is "[*]". This leads to
half-assed editing, as it's very easy to miss one reference and have the
whole thing shifted, no warning is raised, nobody checks, you get a
broken text. Actually, *very* easy if you import texts from unclear
origin.

For what is worth, the additional tool is embedded in amusewiki, and CLI
users should be able to find a way to it.

This is the first thorny point. I'd like that pandoc produce properly
numbered footnotes, instead of doing it the "easy" way of dropping a
[*].

> Maybe it is better not to impose any semantics on footnotes at all
> (not even calling them primary and secondary) so existing texts can
> keep legacy notes as primary and new texts can use new style notes. I
> see adding new footnote style is a chance to make them more usable and
> fix existing problems we have with numbered notes.

Well, a semantic is needed. As you can have secondary footnote inside a
primary footnote, but not the other way around. I think we need to
decide what they mean, before where are they placed and how they look.

Please note: I think it should be fairly ease to add a compiler switch
to do \let\footnote\endnote (something like that) and load the endnote
package. Or tweak the bigfoot settings, swapping roman with alpha, or do
all of them perpage. So, the parser itself should not be concerned about
that. The parser should care to keep track of them an inline/append as
it should.

Back to the semantic: AFAIC, it's clear to me. The primary ones, are the
normal, regular ones. The secondary one, are somehow external to the
original text, and used (when the need actually exists, in some
scholar/critical context) to do further annotation.

> In we talk about web it is possible to reference footnotes by document
> version and anchor like "#fn11". Even if notes are not numbered, they
> will get some anchors anyway. Also, they can be globally numbered
> during compilation even if not numbered in the source.

Another argument for globally numbered footnotes: if you import a text
with an high number of footnotes, you can check right away if all of
them went through or we missed something on the way. Numbering is, by
definition, easier to navigate, instead of wandering where you missed a
footnote and all shifted.

> Also even if both styles can be made equivalent in Text::Amuse, I will
> have to call some notes "footnotes" and some notes "endnotes" in
> pandoc Muse reader. If only one style is used (does not matter which
> one), they can be made "footnotes", but when both of them are used,
> one of them has to be "endnotes" by default. Adding endnotes support
> to pandoc was the source of idea to add new footnote style to Muse and
> I thought to read "[1]" as endnotes, but now it seems inconsistent
> with your view of them.

Well, for me the secondary ones, can be called by pandoc reader as
"endnotes", because less important (i.e., not integral part of the
text), so having out of the way while reading is more acceptable.

> If you don't agree that new style is better, then it is better to
> discuss and redesign them to make them an actual improvement good
> enough to be used as "primary" for new texts.

Yes, better discuss this thing (see the above notes), and see if we can
reach an agreement before burning hours on a feature that nobody is
going to use.

-- 
Marco

**Comment by melmothx** [comment]
I would also like to know the full background of this proposed change and what we want to achieve. I.e. the full problem.

**Comment by labdsf** [comment]
> A bit of history here. In a primitive Text::Amuse implementation, there was the rule what the number was merely a decoration, i.e. only the order counted.

Looks like it is not the case anymore. I have just created this file `misnumbered.muse`:
```
#title misnumbered notes

Notes[1][2]

[2] foo

[1] bar
```

Emacs Muse renders notes in the same (wrong) order in HTML.
```
<!-- Page published by Emacs Muse begins here -->
<p>Notes<sup><a class="footref" name="fnr.1" href="#fn.1">1</a></sup><sup><a class="footref" name="fnr.2" href="#fn.2">2</a></sup></p>

<p class="footnote"><a class="footnum" name="fn.2" href="#fnr.2">2.</a> foo</p>

<p class="footnote"><a class="footnum" name="fn.1" href="#fnr.1">1.</a> bar</p>

<!-- Page published by Emacs Muse ends here -->
```

Internally pandoc has no footnote identifiers:
```
$ pandoc -f muse -t native misnumbered.muse
[Para [Str "Notes",Note [Para [Str "bar"]],Note [Para [Str "foo"]]]]
```

So it just reorders notes:
```
$ pandoc -f muse -t muse misnumbered.muse
Notes[1][2]

[1] bar

[2] foo
```

`muse-compile.pl` produces this:
```
<p>
Notes<a href="#fn1" class="footnote" id="fn_back1">[1]</a><a href="#fn2" class="footnote" id="fn_back2">[2]</a>
</p>

<p class="fnline"><a class="footnotebody" href="#fn_back1" id="fn1">[1]</a> bar
</p>

<p class="fnline"><a class="footnotebody" href="#fn_back2" id="fn2">[2]</a> foo
</p>
```

So pandoc, Text::Amuse and Emacs Muse are consistent here, except that Emacs Muse does not reorder notes properly.

> As in the WIP branch it is "[*]". This leads to half-assed editing, as it's very easy to miss one reference and have the whole thing shifted, no warning is raised, nobody checks, you get a broken text. Actually, *very* easy if you import texts from unclear origin.

What I proposed is a bit different. For example, if footnote is missing, like here
```
Note reference [*].

<comment>[*] Note 1</comment>

Second note reference [*], third note reference [**].

[*] Note 2

[**] Note 3
```
first note reference will refer to Note 2. If you don't allow referencing footnotes multiple times, you can raise an error. Reusable notes better have a name, maybe with a syntax like `[*name]`. So this can not result in missing notes unless you also miss a chunk of text that references this. Other notes don't get shifted etc. So think this syntax has the same drawbacks as "autonumbered" notes. Maybe it has others, like not being able to reference a particular note, but they can be referenced by line number in the source, autonumbered in output formats and referenced by anchor in HTML.

> I would also like to know the full background of this proposed change and what we want to achieve. I.e. the full problem.

I have read some text with author footnotes and commentary endnotes. Thought that it would be impossible to markup in Muse and decided it is probably a good idea to add them. So I implemented endnotes for pandoc, for ODT and Docx first because they are not semantic markup languages and have actual endnotes. After that I started this issue to propose an additional markup for footnotes. At this point I thought of existing notes as endnotes, they are even required to be placed in the end by Emacs Muse (and pandoc, I am working on adding support for Text::Amuse improvements now).

---

As a summary, looks like trying to "improve" the syntax at the same time as adding commentary notes was a bad idea in the first place (as all bikeshedding is). If we are going to just add secondary notes, it can be done without changing the syntax completely:
```
Note reference [1], commentary note reference {1}.

Note reference [2].

[1] Note 1 with commentary reference {2}

[2] Note 2

{1} Commentary reference

{2} Note to note
```
What do you think about implementing this in Text::Amuse instead?

As for syntax extensions, I can add support for writing this as follows in pandoc reader later:
```
Note reference [*], commentary note reference {*}

{*} Commentary reference

[*] Note 1 with commentary reference {*}

{*} Note to note

Note reference [*]

[*] Note 2
```

But even if I do, syntax extension will be optional. Pandoc writer will always write numbers and place notes in the end. Texts without secondary notes will be compatible to Emacs, there will be no "transition" to new syntax, both types of notes will get a new syntax. Seems much better than original idea.

**Comment by labdsf** [comment]
> I thought of existing notes as endnotes, they are even required to be placed in the end by Emacs Muse (and pandoc, I am working on adding support for Text::Amuse improvements now).

By the way pandoc is fixed now: https://github.com/jgm/pandoc/commit/6018a2324d4eddc3844aa4c00b17294e85003750

**Comment by melmothx** [comment]
Summarizing (and please correct me if I got something wrong, the comment
had a lot in it and not fully clear where heading):

 - I add the secondary footnote support syntax, which looks a good idea
   to me. You can consider them as Endnotes in pandoc. New syntax with
   numer inside curly brackets, following the same logic of the primary
   footnotes (so, explicitely numbered), but rendered differently
   (per-page and alpha in latex, to be decided in the HTML). So `{1}`,
   `{2}` etc.

 - The preprocessor tool should cope with them as well (to reorder them,
   if needed).

 - The idea of `[*]` is dropped, as mixing two styles just creates
   confusion at this point.

Still nothing is decided, so you're welcome to comment further.

-- 
Marco

**Comment by labdsf** [comment]
> Summarizing (and please correct me if I got something wrong, the comment had a lot in it and not fully clear where heading):
> ...
> Still nothing is decided, so you're welcome to comment further.

I agree on all three items, looks good.

**Comment by melmothx** [comment]
@labdsf Could you give a try to the secondary footnotes branch? I think it's kind of fine, if I don't find other bugs around. Please note that you need the template fixes in the compiler as in https://github.com/melmothx/text-amuse-compile/commit/7d720c7ea95fef0427cb50991dc55c7c05fbd9c0

**Comment by labdsf** [comment]
@melmothx Thanks, it works. I have two suggestions:

1. Separate primary and secondary notes in HTML
2. Change secondary notes to some other style in TeX. Superscript "a", especially because the counter resets on every page, does not look nice.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> @melmothx Thanks, it works. I have two suggestions:
>
> 1 Separate primary and secondary notes in HTML 

Makes a lot of sense, yes.

> 2 Change secondary notes to some other style in TeX. Superscript "a",
> especially because the counter resets on every page, does not look
> nice.

Suggestions? Roman is confusing, arabic is used in the main footnote.
The other alternative could be *, **, ***, ****, ***** etc. or the
symbols
https://tex.stackexchange.com/questions/36090/alternative-symbol-sets-for-footnote-marks/36105
(which I find a bit too fancy).

-- 
Marco

**Comment by melmothx** [comment]
Regarding the LaTeX style: can be made optional in the compiler, where this choice belong.

@labdsf Another test run if possible, please, and I think that's it. Please use the updated compiler branch, there are some CSS fixes.

**Comment by labdsf** [comment]
> Suggestions? Roman is confusing, arabic is used in the main footnote.

Arabic inside "()":
```
\documentclass{article}
\usepackage[perpage,para]{footmisc}
\usepackage{bigfoot}
\DeclareNewFootnote{default}
\DeclareNewFootnote{B}[alph]
\renewcommand\thefootnote{\arabic{footnote}}
\renewcommand\thefootnoteB{(\arabic{footnoteB})}

\begin{document}

text\footnote{First footnote text text text.} text\footnote{Second footnote.} text\footnote{Third footnote.}
text\footnoteB{Secondary note} text\footnoteB{Secondary note 2}
\end{document}
```

**Comment by labdsf** [comment]
@melmothx Now endnotes are in the end, but I have still found a bug in endnote/footnote ordering in HTML.

Here is an example:
```
#title bug

Author notes that [1].

[1] Author note{1}.

Commentary is {2}.

{1} Commentary about note.

{2} Commentary about text.
```

Notes are in the following order in HTML: [1], {2}, {1}. It should be [1], {1}, {2}.

**Comment by melmothx** [comment]
Fixed, thanks for pointing this out.

**Comment by melmothx** [comment]
Summary status. The preprocessor has been released on CPAN. Text::Amuse CPAN release will follow together with the compiler. Debian packages will follow in a week or two (I'd like to let the cpantesters do some work for me).

**Comment by melmothx** [comment]
modules are on CPAN. The manual will be updated accordingly when the debian packages will be rolled out.

**Comment by melmothx** [comment]
Modules released and packaged, feature documented in the manual. Hence closing this. Thanks again @labdsf
