### ISSUE TITLE
Allow empty comments

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#29]
Empty comments, with a newline immediately following a semicolon, are not parsed as comments:
```
#title ok

Foo
; Comment
;
bar
;
; comment
;
baz
```

HTML output contains three semicolons. Emacs Muse removes them and it seems correct.

**Comment by labdsf** [comment]
By the way Emacs Muse syntax highlighter does not show highlight them as comments. I decided that it is a bug. Pandoc parses these as comments now (in fact it was even more buggy, it consumed a newline as a whitespace and thought that the next line is a comment).

**Comment by melmothx** [comment]
Makes sense, I agree.

**Comment by melmothx** [comment]
Also, the output of the comments is very clumsy and needs refactoring (note to self)

**Comment by melmothx** [comment]
This looks done for me. Reference branch is `pack-comments-29`

Output is greatly improved.
