### ISSUE TITLE
Support for `~~` nonbreaking space replacement

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#30]
Emacs Muse supports `~~` which is replaced by non-breaking space when published. I think it is worth adding to Text::Amuse, along with a preprocessor option to convert non-breaking spaces into `~~`. Good thing is that it is very unlikely to break compatibility.

**Comment by melmothx** [comment]
I'm all for it and I'm glad you brought this up. I wasn't aware of this code in emacs muse.

**Comment by labdsf** [comment]
Also there are `--` and `---`, both of them are replaced with em dash. I wonder why `--` is not en dash, but it looks like it was intended this way.

**Comment by melmothx** [comment]
This looks done for me. Reference branch is `pack-comments-29`
