### ISSUE TITLE
<code> is not verbatim

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#33]
Example:

```
#title ok

<code>abc<br>def</code>

=abc<br>def=
```

Emacs Muse escapes `<br>` tag in this case.

[Emacs Muse manual](https://www.gnu.org/software/emacs-muse/manual/muse.html#Emphasizing-Text) says that `=` and `<code>` means "verbatim and monospace".

Text::Amuse manual changed it to "code and monospace".

The difference in behaviour is not documented as a difference in Text::Amuse manual. Is it a bug in Text::Amuse or in the manual?

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> Example:
>
> ```
> #title ok
>
> <code>abc<br>def</code>
>
> =abc<br>def=
> ```
>
> Emacs Muse escapes `<br>` tag in this case.
>
> [Emacs Muse manual](https://www.gnu.org/software/emacs-muse/manual/muse.html#Emphasizing-Text) says that `=` and `<code>` means "verbatim and monospace".
>
> Text::Amuse manual changed it to "code and monospace".
>
> The difference in behaviour is not documented as a difference in
> Text::Amuse manual. Is it a bug in Text::Amuse or in the manual?

This looks more like a "wrong implementation because of confusing
specification".

It makes sense to consider the the code tag a verbatim one, yes.

--
Marco

**Comment by melmothx** [comment]
@labdsf  Mind to review 4a8dca2 ?

**Comment by labdsf** [comment]
Installed and tested it, works for me.
