### ISSUE TITLE
=<verbatim>= and <code><verbatim></code>

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#37]
`amusewiki-site/m/ml/manual.muse` compilation produces warnings because of this.

This line just checks if there is a "verbatim" tag inside code:
https://github.com/melmothx/text-amuse/blob/375ffe0b919b659e11881e862589728d34bbc670/lib/Text/Amuse/InlineElement.pm#L195

Maybe produce warning only in `<code><verbatim>(.*)<\/verbatim><\/code>` case instead?

**Comment by melmothx** [comment]
Thanks!
