### ISSUE TITLE
Heading anchors should be on top of headings

### ISSUE THREAD

**Issue by link2xt** [melmothx/text-amuse#39]
For example (home page of Alex Ott, Emacs Muse maintainer):
https://github.com/alexott/alexott.github.com/blob/f8ba12b44bb2b7535277e313bff181ac77995f6b/ru/clojure/ClojureHadoop.muse#L310

Emacs Muse produces this code:
```
<h2><a name="more-info" id="more-info"></a>Дополнительная информация</h2>
```

Text::Amuse produces a separate paragraph (I changed `#more-info` to `#moreinfo`, because Text::Amuse does not allow "-" in anchors):
```
<p>
<a id="text-amuse-label-moreinfo" class="text-amuse-internal-anchor"></a>

</p>
<h2 id="toc1">Дополнительная информация</h2>
```
The manual also suggests placing anchors below the heading:
https://github.com/melmothx/amusewiki-site/blob/c70d7e2047868c8ffe4aa77ab66dd7af7869b81c/m/ml/manual.muse#L1315

pandoc mimics Text::Amuse here (and has problems with "-" in anchor too). As I am refactoring heading parsing (see issue #38) anyway, I am going to change it towards Emacs Muse implementation. It makes more sense to me, because anchor is not moved from the end of heading text to the beginning. If there is no good reason for this change, I consider it to be a bug of Text::Amuse.

Not really urgent to fix. We may want to fix manual now, though, if the bug is confirmed, so there are less compatibility problems once the bug is fixed.

----

Another example, from Java implementation of Muse:
https://github.com/abailly/muse-parser/blob/449f81df49524f22871afb009f778ba493bb2fc8/src/site/muse/maven-muse.muse#L72

**Comment by melmothx** [comment]
Actually I don't think emacs-muse is much wiser than Text::Amuse. See the following example

```
#title Prova

Starting here

#moreinfo1
** More info 1
#hello1


#moreinfo2 and more
** More info 2
#hello2 and more
```

Resulting in:

```
    <!-- Page published by Emacs Muse begins here -->
<p>Starting here</p>

<h3><a name="moreinfo1" id="moreinfo1"></a>More info 1</h3>

<p><a name="hello1" id="hello1"></a>
<a name="moreinfo2" id="moreinfo2"></a>
and more</p>


<h3>More info 2</h3>

<p><a name="hello2" id="hello2"></a>
and more</p>
```

I'm not saying that this shouldn't be fixed, just pointing out the inconsistency of the original implementation and that we should find out a logic behind all this mess.

**Comment by melmothx** [comment]
From a quick look at the code, i think this can't be done cleanly without a refactoring of the block level parsing. Other issues which go beyond the parser limits are also #35 #36 (even if I suspect this one is probably an impossible mission).

I'm willing to refactor and accomodate for a more flexible parsing, but I have other things with higher priority coming first (as these are cross-implementation incompatibilities and corner cases, not really defects).

So, let's find out what the common definitions for anchors should be, but I can't promise a release implementing it before a couple of months.

**Comment by melmothx** [comment]
More Emacs Muse bugs:

```
Starting here

#moreinfo1
*More info 1b*
#hello1


#moreinfo2 and more
*More info 2*
#hello2 and more
```

```
Starting here

\label{moreinfo1}\emph{More info 1b}
\label{hello1}\#moreinfo2 and more
\emph{More info 2}
\label{hello2}and more
```

So, I don't think that the idea of having anchor + other material on the same physical line is a good idea (as in Emacs Muse, which gets it wrong at least in the above scenario). On the other hand, such anchors should be placed after or before  a paragraph, without blank lines separating it. In the middle is a bit confusing and random.

```
#validbefore
paragraph

paragraph
#validafter

paragraph
#label
paragraph. Unclear. Probably nobody cares what happens.

#label with material, this should be invalid. 
There is no reason not to hit enter and continue on the line above.

#before
** heading, this is ok

** heading after, this is ok as well
#after
```

Thoughts?

**Comment by labdsf** [comment]
> So, I don't think that the idea of having anchor + other material on the same physical line is a good idea (as in Emacs Muse, which gets it wrong at least in the above scenario).

The bug with emphasis is in LaTeX publishing code, HTML is correct:
```
<p>Starting here</p>

<p><em><a name="moreinfo1" id="moreinfo1"></a>More info 1b</em>
<a name="hello1" id="hello1"></a>
<a name="moreinfo2" id="moreinfo2"></a>
and more
<em>More info 2</em>
<a name="hello2" id="hello2"></a>
and more</p>
```

Additional material on the same line is possible, the only restriction is that anchor is at the beginning of the line.

> On the other hand, such anchors should be placed after or before a paragraph, without blank lines separating it. In the middle is a bit confusing and random.

Anchors can be placed anywhere at the beginning of a line. I think everything is ok except for anchor at the end of the paragraph. It confuses Emacs Muse, making it merge the next paragraph with the current one. And Emacs Muse allows user to set `muse-html-anchor-on-word` option to make `<a>` tag surround the next word, which does not make sense if there is no next word.

The following code is valid:
```
Startinghere

#validbefore Paragraph start
middle
#validmiddle end
```

It produces paragraph "Paragraph start middle end" with two anchors inside.

The following code should attach anchor to section contents, not to heading, IMO:
```
** heading after, this is ok as well
#after
```

**Comment by melmothx** [comment]
Ok for the random placement in the middle of something, but regarding the heading label the after tag should attach to the adjacent block, regardless if after/before. Visually it is attached to the preceding element, not to the next. If you want attached to the next, you skip the line. In Emacs Muse it doesn't and merges to the next paragraph, but that still looks like a bug to me. The original manual is very laconic.

So, I believe that most of the Emacs Muse users will use an adjacent anchor before the title or the paragraph, and avoid after anchor (which eats the paragraph separator). But the Text::Amuse manual said differently and more extensively (rather than just: If you begin a line with "#anchor" – where "anchor" can be any word that doesn't contain whitespace – it defines an anchor at that point into the document.). Now it's too late to take it back.

So, I agree to implement the label before the section headings, with the rule that the anchor attaches to adjacent element, regardless of its position. I think you can do the same in amuse headings extension to support that, but still, it's not a groundbreaker, as linking to a section body or to its title has more or less the same meaning.

Finally, I think that the paragraph eating for end of block labels should be threated as a (wont-fix) bug in Emacs Muse.

Does this sound fair enough?

**Comment by labdsf** [comment]
> So, I agree to implement the label before the section headings, with the rule that the anchor attaches to adjacent element, regardless of its position.

Ok, agreed. Attaching anchor from previous paragraph to the next is a bug indeed.

The following code
```
#bar
* Foo
#baz
```
should translate to
```
<h2><a name="bar"></a>Foo<a name="baz"></a></h2>
```
or something similar (two anchors, at the beginning and at the end of heading).

**Comment by melmothx** [comment]
Ok, the specification looks complete to me. I hope to have some working code soon, but I need to refactor some naive code. And, at this point, better to do it properly than hack it quickly.

**Comment by melmothx** [comment]
@labdsf the branch `labels-39` to me looks good to go. Would you mind giving it a try before I merge it? Please note that the anchors will stack at the beginning of the block, regardless of their position inside the string. This is mainly an implementation artifact, but it doesn't seem a show-stopper to me.

**Comment by labdsf** [comment]
@melmothx 
I have just installed it and checked, everything is good on real files, anchors are attached to corresponding headers.
