### ISSUE TITLE
Add support for named anchors

### ISSUE THREAD

**Issue by racke** [melmothx/text-amuse#4]
Like in HTML, this is useful for internal linking within a document.

**Comment by melmothx** [comment]
Supported in the original specification

https://www.gnu.org/software/emacs-muse/manual/muse.html#Horizontal-Rules-and-Anchors

**Comment by melmothx** [comment]
This is done, but still needs support on the compiler for epub (where the html is splitted) and for merging (where the anchors need to be disambiguated).
