### ISSUE TITLE
muse-compile.pl produces nothing if there is an empty heading

### ISSUE THREAD

**Issue by labdsf** [melmothx/text-amuse#40]
How to reproduce: try to compile the following with `muse-compile.pl 1.muse --html`.

```
#title Bug

* Bug title

This text is not displayed

* <verbatim></verbatim>

ok
```

Only a horizontal rule is emitted, which separates footnotes. Adding anything into `<verbatim>` and recompiling fixes the bug.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> Only a horizontal rule is emitted, which separates footnotes. Adding
> anything into <verbatim> and recompiling fixes the bug.

Yes, it's a crash in the parser as it assumes that the header returns a
non-empty string. Normally doesn't happen, but the <verbatim> tag fools
it.

I'm mumbling a fix, as there could be some side effects in the
downstream.

Please note that "** ~" works fine for an empty header.

--
Marco

**Comment by melmothx** [comment]
See 217b91e

**Comment by labdsf** [comment]
> Please note that "** ~" works fine for an empty header.

I don't really need empty headers, but `pandoc` produces this `<verbatim></verbatim>` when the source document has them.

> See 217b91e

I have installed and tested the new version, it works. Thanks. Closing PR.
