### ISSUE TITLE
Mark different language inside a text.

### ISSUE THREAD

**Issue by melmothx** [melmothx/text-amuse#42]
I'd need to add a markup rule for switching directions to support RTL languages (farsi upcoming).

@labdsf suggestions for a tag name? I was thinking about `<rtl>` `<ltr>` which should be self-explanatory.

**Comment by labdsf** [comment]
@melmothx What do you plan to generate in the output? Probably a `<div>` with a `dir` attribute?

In this case, I suggest to introduce support for the `<div>` tag, which was there in Emacs Muse, but is not supported in Amusewiki. Emacs Muse supports only `id` and `style` attributes, but in pandoc Muse Reader just parses all the attributes, so you can already use it like this:
```
#title RTL test

<div dir="rtl">
foo
</div>
```
Pandoc generates identical HTML output for this `<div>` tag. For LaTeX, pandoc includes `bidi` package and uses RTL and LTR environments. As for the metadata, please use `#dir rtl` and `#dir ltr`, it seems that is what pandoc uses.

I have never thought about RTL support in pandoc Muse reader/writer and was actually surprised that it already works. There is a discussion in pandoc issues: https://github.com/jgm/pandoc/issues/2191 And a PR that added support: https://github.com/jgm/pandoc/pull/2419

In general, I don't like the approach of adding new tags. I even think `<biblio>` and `<play>` should have been `<div class="biblio">` and `<div class="play">`. This way it would have stayed compatible with Emacs Muse, even though Emacs Muse just ignores the `class` and the styling would be lost.

**Comment by melmothx** [comment]
Alexander <notifications@github.com> writes:

> @melmothx What do you plan to generate in the output? Probably a
> `<div>` with a `dir` attribute?

No, normally a <span dir="(rtl|ltr)"> element. The <div> would be for a
whole paragraph. The primary concern here is not a whole english
paragraph in the middle of a persian text, but a short chunk of english
inside a persian sentence. Specifically, I'm thinking about citation of
foreign titles. LaTeX needs to know about that.

> In this case, I suggest to introduce support for the `<div>` tag,
> which was there in Emacs Muse, but is not supported in Amusewiki.
> Emacs Muse supports only `id` and `style` attributes, but in pandoc
> Muse Reader just parses all the attributes, so you can already use it
> like this: ``` #title RTL test
> <div dir="rtl">
> foo
> </div>
> ```

Here I don't agree. That div with attributes is not a lightweight markup
element, it's a dive into XML. For a period I was using a subset of HTML
as lightweight markup, and I truly hated it.

 - easy to type it wrong
 - long to type
 - ugly to see
 - needs special care when appling the typographical quotes
 - parser needs to be relaxed
 - it's not semantic. A "div" means absolutely nothing.

> Pandoc generates identical HTML output for this `<div>` tag. For
> LaTeX, pandoc includes `bidi` package and uses RTL and LTR
> environments. As for the metadata, please use `#dir rtl` and `#dir
> ltr`, it seems that is what pandoc uses.

The #dir directive in the header is totally redundant if you declare the
language.

> In general, I don't like the approach of adding new tags. I even think
> `<biblio>` and `<play>` should have been `<div class="biblio">` and
> `<div class="play">`. This way it would have stayed compatible with
> Emacs Muse, even though Emacs Muse just ignores the `class` and the
> styling would be lost.

See above for the general approach.

Tags per se are ugly though. Even typing <example></example> is a pain.
That's why {{{ and }}} were introduced, which work well and are nice to
type.

After mumbling, I'm inclined to use <<< >>> and >>> <<<.

I'm asking an advise to the persons using it.

--
Marco

**Comment by melmothx** [comment]
Useful doc for HTML implementation:
https://www.w3.org/International/articles/inline-bidi-markup/

**Comment by melmothx** [comment]
This is done. For my testing it's working correctly and it's not hateful to type (`<<<` and `>>>`, both for blocks and for inline sentences). The feature is still marked as experimental until there is someone actually using that and providing feedback.

**Comment by melmothx** [comment]
This needs to be revamped.

After some experience with other languages, this bidi-specific solution is not good.

Instead, recent `babel` package has the bidi support built in switching languages.

What's missing is a way to mark the foreign languages inside a paragraph.

So I want be able to mark a part of a sentence as, for example, English, inside an Arabic paragraph, and the other way around.

**Comment by melmothx** [comment]
Markup to be used is up for discussion.

**Comment by melmothx** [comment]
Babel example

```
\documentclass{book}
\usepackage[croatian,english,arabic,bidi=default,provide*=*]{babel}
\usepackage{fontspec}
\setmainfont{Amiri}

```

**Comment by melmothx** [comment]
This was done in 18d4b58
