### ISSUE TITLE
Table specification

### ISSUE THREAD

**Issue by melmothx** [melmothx/text-amuse#59]
Currently the tables generated by the module have a fixed specification, expand and justify, which plays out decently but not great most of the time.

So, I'm going to introduce a specification line to the table syntax, something like this:

```
|# crlX|X|c| #|
```

Where the string inside the line is the same as the tabular/tabularx LaTeX environment, where the character can be c (center), r(right), l (left), X (justified), pipe (line between columns).

Low priority: apply to HTML as well.

I think that having a specification is way better than some heuristics based on whitespace or similar.

Comments welcome @link2xt

**Comment by racke** [comment]
Commas as separators instead of pipes would be a huge improvement for readability.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> Commas as separators instead of pipes would be a huge improvement for readability.

Problem is that the pipes are not a separator, they are part of the
specification (vertical bars between columns).

Whitespace should be permitted for readability, like "| X | c  r  l |".

-- 
Marco

**Comment by racke** [comment]
Which specification you are talking about?

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> Which specification you are talking about?

The LaTeX's tabular one, which are going to be borrowed and used. For
example:

\begin{tabularx}{\textwidth}{|r|l|X|}
 1        &        1   &  lorem ipsum \\
\end{tabularx}

The pipes here are the vertical bars, as opposed to:

\begin{tabularx}{\textwidth}{rlX}
 1        &        1   &  lorem ipsum \\
\end{tabularx}

(No bars)

-- 
Marco

**Comment by racke** [comment]
Sorry, but why would the user care about the LaTeX specification? And it is really straightforward to turn pipes into commas anyway.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> Sorry, but why would the user care about the LaTeX specification? And
> it is really straightforward to turn pipes into commas anyway.

It all depends on which user :-)

The extension we're talking about is completely optional, of course. The
problem is that sometimes there's a need to have more control over the
output. With bars or without, cells centered/left/right/justified.

Now the idea here is that the LaTeX specification should be borrowed and
used, instead of inventing a new one.

This issue with tables is a non-issue on HTML, where the output is
usually good. Not so with LaTeX, because it needs to be hinted. I've
been mumbling over this problem for a while and now I have a use case
where the current output is not good.

Now, back to the problem. The pipes in the specification are not field
separators, they are saying that the table should have vertical bars
between cells, so using commas there makes no sense. There's no need for
them. Space can be used for readability.

Am I making sense?

-- 
Marco

**Comment by racke** [comment]
Actually HTML display could take advantage of hints like that. I would prefer some syntax like GitHub uses (https://help.github.com/en/github/writing-on-github/organizing-information-with-tables) instead of your proposal.

**Comment by racke** [comment]
You usually use either bars or no bars for the whole table.

**Comment by melmothx** [comment]
Stefan Hornburg (Racke) <notifications@github.com> writes:

> Actually HTML display could take advantage of hints like that. I would
> prefer some syntax like GitHub uses
> (https://help.github.com/en/github/writing-on-github/organizing-information-with-tables)
> instead of your proposal.

Ok, that could look reasonable, but dropping the vertical bars in the
LaTeX output (which I think it's reasonable as well).

-- 
Marco

**Comment by melmothx** [comment]
This has been released and documented.
