### ISSUE TITLE
Add <verbatim> (was: <literal>) support.

### ISSUE THREAD

**Issue by ilabdsf** [melmothx/text-amuse#8]
I know what [the manual](https://amusewiki.org/library/manual) says about `<literal>`:
> There is no `<literal>` tag as in the original Muse markup, because it’s not a private tool and will be exposed to the internet.

However, `<literal>` can be made secure by HTML escaping its contents. This way it can be used to solve issue #7 by making it possible to write `<literal>[1]</literal>` at the beginning of the line.

I am currently working on [Muse writer for pandoc](https://github.com/jgm/pandoc/issues/3405) and have a problem with escaping tags. If you add `<literal>` support, I could escape tags like `<literal><code></literal>` and even the `</literal>` itself with a bit tricky `<literal><</literal><literal>/literal></literal>`.

@melmothx 
If you agree, I would assume it is supported while writing pandoc Muse writer and then either wait for you to add `<literal>` or try to make a PR myself (but only after Muse writer is accepted in pandoc since I really want to finish it).

**Comment by melmothx** [comment]
This could be a solution indeed. But resulting in an escaped output. I need to check the original implementation how it behaves.

**Comment by melmothx** [comment]
@ilabdsf 

https://www.gnu.org/software/emacs-muse/manual/muse.html#Paragraphs it looks like it's not what it was meant for, though.

What exactly is the problem you're trying to solve? It's for the documentation, for a sample, or for the code itself?

**Comment by melmothx** [comment]
Another solution, which breaks the compatibility with the original implementation (which btw looks very much dead), would be to add a <null> tag. This way you could neutralize anything just inserting it in the middle. Like <<null>code>

Thoughts?

**Comment by ilabdsf** [comment]
Looks like the tag I was looking for is `<verbatim>`.

**Comment by melmothx** [comment]
It sounds sensible and back-compatible. I'm going to do some coding over the next days, but I guess that's the solution.

**Comment by melmothx** [comment]
This is done in master. I'll do a release over the next days.
