### ISSUE TITLE
Nested <code> and = produce strange output

### ISSUE THREAD

**Issue by ilabdsf** [melmothx/text-amuse#9]
If I nest code tag and markup like `=<code>abc</code>=` or like `<code>=abc=</code>`, I get the same HTML output in both cases:
```
<p>
<code>&lt;code&gt;abc</code>&lt;/code&gt;
</p>
```

Shouldn't it be
```
<p>
<code>&lt;code&gt;abc&lt;/code&gt;</code>
</p>
```
instead?

For LaTeX results are similar, I get
```
\texttt{<code>abc}<\Slash{}code>
```

**Comment by melmothx** [comment]
Not sure it's really a concern, as nesting the same tag (which `=` expands to) makes no sense.

In the first pass, = gets expanded. When the actual replacement is done, the regular expression gets confused.

**Comment by ilabdsf** [comment]
> In the first pass, = gets expanded.

I have not read the code actually, is it expanded to `<code><code>abc</code></code>`?

> nesting the same tag makes no sense.

As `=` means "verbatim and monospace", I thought it should expand to verbatim code tags inside real code tags in first case and in verbatim `=` inside code tags in second case.

Now instead of "verbatim and monospace" it means "verbatim as long as there are no </code> tags inside and monospace".

> Not sure it's really a concern

Ok, it is not high-priority, I just wanted to make sure it is a bug and not some sort of a feature I am not aware of. I will just use `<code>` like if it works correctly then.

**Comment by melmothx** [comment]
Alexander Krotov <notifications@github.com> writes:

>> In the first pass, = gets expanded.
>
> I have not read the code actually, is it expanded to `<code><code>abc</code></code>`?

Yes. `=` is actually a concise way to write `<code>` (exactly like `*`
for `<em>`). So, like nesting `<em>` makes no sense, nesting `<code>`
makes no sense and you get an undefined behaviour, mostly likely buggy
and definitively not what you wanted.

>> nesting the same tag makes no sense.
>
> As `=` means "verbatim and monospace", I thought it should expand to verbatim code tags inside real code tags in first case and in verbatim `=` inside code tags in second case.
>
> Now instead of "verbatim and monospace" it means "verbatim as long as there are no </code> tags inside and monospace".

Ok I agree that "verbatim" is just confusing. After the release with the
`<verbatim>` support (which I assume it's what you wanted), I'll fix the
documentation.

>> Not sure it's really a concern
>
> Ok, it is not high-priority, I just wanted to make sure it is a bug and not some sort of a feature I am not aware of. I will just use `<code>` like if it works correctly then.

I guess you want to nest `<verbatim>` inside `<code>` (or the other way
around), which is (and I will make sure it works) totally fine.

Or am I missing something? If so, please give me a document snippet I
can stuff in the test suit.

Thanks!

-- 
Marco
